security:
    encoders:
        App\Entity\User:
            algorithm: argon2i
            
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
